### PR TITLE
Accelerate analysis by loading file once, not twice

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by zohreb** [comment]
نصب و راه اندازی

**Comment by zohreb** [comment]
67bf157

**Comment by schollz** [comment]
@cclauss Something is wrong with this change...it runs much much slower.

When I run `howmanypeoplearearound -z file.json` using this patch it it takes about 10 seconds before it even starts the server. The current version only takes ~ 1 second.

**Comment by cclauss** [comment]
Sorry.  The set() trick is usually superfast but in this case, the unnecessary append()s added up.

**Comment by schollz** [comment]
Great thanks!

**Comment by zohreb** [comment]
GitHub:
I'm a GitHub bot. I can notify you about events in your public GitHub repositories. You can also reply to my messages to post comments to GitHub right from Telegram.

Available commands:
/connect - Authorize bot via OAuth
/newintegration - Add integration with a GitHub repository
/listintegrations - List all current integrations
/delintegration - Delete integration
/cancel - Cancel the current command

**Comment by zohreb** [comment]
GitHub:
I'm a GitHub bot. I can notify you about events in your public GitHub repositories. You can also reply to my messages to post comments to GitHub right from Telegram.

Available commands:
/connect - Authorize bot via OAuth
/newintegration - Add integration with a GitHub repository
/listintegrations - List all current integrations
/delintegration - Delete integration
/cancel - Cancel the current command

**Comment by zohreb** [comment]
ایجاد تغییرات برای این دستورات

**Pull request merged**
