### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by cclauss**
Trying to fix https://github.com/schollz/howmanypeoplearearound/issues/6  This does the full build but does not provide any data packets on my Mac but maybe others will have more luck on more promiscuous OSes.

To use:
* $ `docker build -t howmanypeoplearearound .`
* $ `docker run -it --rm --name howmanypeoplearearound howmanypeoplearearound`

### CODE REVIEW

**Comment by schollz** [comment]
@cclauss Fantastic! Really nice work.

**Comment by cclauss** [comment]
Thanks but does it actually allow you to collect packets?  It does not on Docker for Mac.

**Comment by schollz** [comment]
Yes. You have to add `--net=host` and it works just fine for me for Docker on Ubuntu

**Comment by cclauss** [comment]
Add `add --net=host` on which command?

We need to add something on how to use the Dockerfile into README.md.

**Pull request merged**
