### PR TITLE
adding OSX support and cleanup

### PR DESCRIPTION
**Pull request by taylorsmithgg**
Added some documentation + prompts for osx support.
Used netifaces to list network adapters to prevent needing to ifconfig.

### CODE REVIEW

**Comment by schollz** [comment]
Thanks! Looks really nice. One question - Does this require sudo to run now? On my Chromebook it requires sudo to access ifconfig...I wanted to avoid having people run this in sudo unless it's really worth it.

**Comment by taylorsmithgg** [comment]
I didn't need it on my system, but I didn't do extensive testing. 
Seems like netifaces doesn't either since it is a python lib.

**Comment by schollz** [comment]
Oh sorry, can you fix it to work on Python3?
It should be cross compatible, you just need to put back the parentheses around the print statements.

**Comment by taylorsmithgg** [comment]
Done & Done

**Pull request merged**
